server:
  port: 8081
spring:
  application: 
    name: item-service
  cloud:
    refresh:
      refreshable: none
  datasource:
    url: jdbc:mysql://172.16.8.41:3306/mall
    username: mysql
    password: mysql
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  

mybatis:
# spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 
eureka: 
  client:
    service-url:
      defaultZone: http://172.16.8.49:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 172.16.7.228
    instance-id: ${spring.application.name}:${server.port}
    
